CPP := g++
CPP_FLAGS := -Wall -m64 -gdwarf-2 -std=c++17 -c

ASM := yasm
ASM_FLAGS := -f elf64 -gdwarf2

LINKER := g++
LINKER_FLAGS := -Wall -m64 -gdwarf-2 -no-pie -z noexecstack

BIN_NAME: main
BIN := ./$(BIN_NAME)

run:	build
	@echo "Running Program!"
	$(BIN)
.PHONY: run

build:	$(BIN)
.PHONY:	run

$(BIN):	driver.o hello.o
	$(LINKER) $(LINKER_FLAGS) *.so *.o *-o "$@"
	
driver.o:	driver.cpp
	$(CPP) $(CPP.FLAGS) "$<" -o "$@"
	
hello.o:	hello.asm
	$(ASM) $(ASM_FLAGS) "$<" -o "$@"
	
clean:
	-rm *.o
	-rm $(BIN)
.PHONY: clean
